#ifndef GRCL_C_DIAGNOSTICS_H_
#define GRCL_C_DIAGNOSTICS_H_

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum grcl_diagnostic_severity {
  GRCL_DIAGNOSTIC_SEVERITY_UNKNOWN = 0x0000,
  GRCL_DIAGNOSTIC_SEVERITY_INFO = 0x0001,
  GRCL_DIAGNOSTIC_SEVERITY_WARNING = 0x0002,
  GRCL_DIAGNOSTIC_SEVERITY_ERROR = 0x0003,
  GRCL_DIAGNOSTIC_SEVERITY_FATAL = 0x0004
} grcl_diagnostic_severity_t;

typedef enum grcl_diagnostic_category {
  GRCL_DIAGNOSTIC_CATEGORY_UNKNOWN = 0x0000,
  GRCL_DIAGNOSTIC_CATEGORY_CALLER_ERROR = 0x0001,
  GRCL_DIAGNOSTIC_CATEGORY_RESOURCE = 0x0002,
  GRCL_DIAGNOSTIC_CATEGORY_COMPATIBILITY = 0x0003,
  GRCL_DIAGNOSTIC_CATEGORY_RUNTIME = 0x0004,
  GRCL_DIAGNOSTIC_CATEGORY_GRAPH_SESSION = 0x0005,
  GRCL_DIAGNOSTIC_CATEGORY_STORAGE = 0x0006,
  GRCL_DIAGNOSTIC_CATEGORY_ALLOCATOR = 0x0007,
  GRCL_DIAGNOSTIC_CATEGORY_CAPABILITY = 0x0008
} grcl_diagnostic_category_t;

typedef enum grcl_diagnostic_scope {
  GRCL_DIAGNOSTIC_SCOPE_UNKNOWN = 0x0000,
  GRCL_DIAGNOSTIC_SCOPE_RUNTIME = 0x0001,
  GRCL_DIAGNOSTIC_SCOPE_NODE = 0x0002,
  GRCL_DIAGNOSTIC_SCOPE_ENDPOINT = 0x0003,
  GRCL_DIAGNOSTIC_SCOPE_SESSION = 0x0004,
  GRCL_DIAGNOSTIC_SCOPE_CHANNEL = 0x0005,
  GRCL_DIAGNOSTIC_SCOPE_GRAPH = 0x0006,
  GRCL_DIAGNOSTIC_SCOPE_STORAGE = 0x0007,
  GRCL_DIAGNOSTIC_SCOPE_ALLOCATOR = 0x0008
} grcl_diagnostic_scope_t;

typedef enum grcl_diagnostic_code {
  GRCL_DIAGNOSTIC_CODE_NONE = 0x0000,
  GRCL_DIAGNOSTIC_CODE_INVALID_ARGUMENT = 0x0101,
  GRCL_DIAGNOSTIC_CODE_BAD_STATE = 0x0102,
  GRCL_DIAGNOSTIC_CODE_OUT_OF_MEMORY = 0x0201,
  GRCL_DIAGNOSTIC_CODE_CAPACITY_EXCEEDED = 0x0202,
  GRCL_DIAGNOSTIC_CODE_UNSUPPORTED_CAPABILITY = 0x0301,
  GRCL_DIAGNOSTIC_CODE_INCOMPATIBLE_VERSION = 0x0302,
  GRCL_DIAGNOSTIC_CODE_TIMEOUT = 0x0401,
  GRCL_DIAGNOSTIC_CODE_INTERRUPTED = 0x0402,
  GRCL_DIAGNOSTIC_CODE_BACKEND_FAILURE = 0x0403,
  GRCL_DIAGNOSTIC_CODE_PEER_UNAVAILABLE = 0x0501,
  GRCL_DIAGNOSTIC_CODE_CHANNEL_REJECTED = 0x0502,
  GRCL_DIAGNOSTIC_CODE_STORAGE_REGION_MISSING = 0x0601,
  GRCL_DIAGNOSTIC_CODE_STORAGE_ALIGNMENT_UNSUPPORTED = 0x0602,
  GRCL_DIAGNOSTIC_CODE_ALLOCATOR_UNAVAILABLE = 0x0701,
  GRCL_DIAGNOSTIC_CODE_UNKNOWN = 0x7fff
} grcl_diagnostic_code_t;

struct grcl_diagnostic_record {
  size_t struct_size;
  uint32_t abi_version;
  grcl_diagnostic_code_t code;
  grcl_diagnostic_severity_t severity;
  grcl_diagnostic_category_t category;
  grcl_diagnostic_scope_t scope;
  uint32_t detail_flags;
};

#ifdef __cplusplus
}
#endif

#endif  /* GRCL_C_DIAGNOSTICS_H_ */
